In [1]:
from keras.models import Sequential
from keras.layers import Dense
import numpy

# fix random seed for reproducibility
seed = 7
numpy.random.seed(seed)

Using TensorFlow backend.


In [2]:
# load pima indians dataset
dataset = numpy.loadtxt("pima-indians-diabetes.csv", delimiter=",")
# split into input (X) and output (Y) variables
X = dataset[:,0:8]
Y = dataset[:,8]

In [22]:
dataset[:5]

array([[  6.00000000e+00,   1.48000000e+02,   7.20000000e+01,
          3.50000000e+01,   0.00000000e+00,   3.36000000e+01,
          6.27000000e-01,   5.00000000e+01,   1.00000000e+00],
       [  1.00000000e+00,   8.50000000e+01,   6.60000000e+01,
          2.90000000e+01,   0.00000000e+00,   2.66000000e+01,
          3.51000000e-01,   3.10000000e+01,   0.00000000e+00],
       [  8.00000000e+00,   1.83000000e+02,   6.40000000e+01,
          0.00000000e+00,   0.00000000e+00,   2.33000000e+01,
          6.72000000e-01,   3.20000000e+01,   1.00000000e+00],
       [  1.00000000e+00,   8.90000000e+01,   6.60000000e+01,
          2.30000000e+01,   9.40000000e+01,   2.81000000e+01,
          1.67000000e-01,   2.10000000e+01,   0.00000000e+00],
       [  0.00000000e+00,   1.37000000e+02,   4.00000000e+01,
          3.50000000e+01,   1.68000000e+02,   4.31000000e+01,
          2.28800000e+00,   3.30000000e+01,   1.00000000e+00]])

In [23]:
X[:5]

array([[  6.00000000e+00,   1.48000000e+02,   7.20000000e+01,
          3.50000000e+01,   0.00000000e+00,   3.36000000e+01,
          6.27000000e-01,   5.00000000e+01],
       [  1.00000000e+00,   8.50000000e+01,   6.60000000e+01,
          2.90000000e+01,   0.00000000e+00,   2.66000000e+01,
          3.51000000e-01,   3.10000000e+01],
       [  8.00000000e+00,   1.83000000e+02,   6.40000000e+01,
          0.00000000e+00,   0.00000000e+00,   2.33000000e+01,
          6.72000000e-01,   3.20000000e+01],
       [  1.00000000e+00,   8.90000000e+01,   6.60000000e+01,
          2.30000000e+01,   9.40000000e+01,   2.81000000e+01,
          1.67000000e-01,   2.10000000e+01],
       [  0.00000000e+00,   1.37000000e+02,   4.00000000e+01,
          3.50000000e+01,   1.68000000e+02,   4.31000000e+01,
          2.28800000e+00,   3.30000000e+01]])

In [24]:
Y[:5]

array([ 1.,  0.,  1.,  0.,  1.])

In [25]:
# create model
model = Sequential()
model.add(Dense(12, input_dim=8, init='uniform', activation='relu'))
model.add(Dense(8, init='uniform', activation='relu'))
model.add(Dense(1, init='uniform', activation='sigmoid'))

In [26]:
# Compile model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [27]:
# Fit the model
model.fit(X, Y, nb_epoch=150, batch_size=10)

Epoch 1/150
768/768 [==============================] - 0s - loss: 0.6843 - acc: 0.6172     
Epoch 2/150
768/768 [==============================] - 0s - loss: 0.6649 - acc: 0.6510     
Epoch 3/150
768/768 [==============================] - 0s - loss: 0.6530 - acc: 0.6523     
Epoch 4/150
768/768 [==============================] - 0s - loss: 0.6424 - acc: 0.6563     
Epoch 5/150
768/768 [==============================] - 0s - loss: 0.6281 - acc: 0.6732     
Epoch 6/150
768/768 [==============================] - 0s - loss: 0.6182 - acc: 0.6758     
Epoch 7/150
768/768 [==============================] - 0s - loss: 0.6100 - acc: 0.6706     
Epoch 8/150
768/768 [==============================] - 0s - loss: 0.6025 - acc: 0.6888     
Epoch 9/150
768/768 [==============================] - 0s - loss: 0.5991 - acc: 0.6810     
Epoch 10/150
768/768 [==============================] - 0s - loss: 0.5920 - acc: 0.6901     
Epoch 11/150
768/768 [==============================] - 0s - loss: 0.5924 - acc

In [28]:
# evaluate the model
scores = model.evaluate(X, Y)
print("\n%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))
scores

768/768 [==============================] - 0s     

acc: 77.73%


[0.45839844644069672, 0.77734375]

In [29]:
probabilities = model.predict(X)
predictions = [float(round(x)) for x in probabilities]
accuracy = numpy.mean(predictions == Y)
print("Prediction Accuracy: %.2f%%" % (accuracy*100))

Prediction Accuracy: 77.73%
