In [3]:
import numpy as np

embedding_size = 4
vocab_size = 10

embedding = np.arange(embedding_size * vocab_size, dtype='float')
print(embedding.shape)
print(embedding)

embedding = embedding.reshape(vocab_size, embedding_size)
print(embedding)

(40,)
[  0.   1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.  14.
  15.  16.  17.  18.  19.  20.  21.  22.  23.  24.  25.  26.  27.  28.  29.
  30.  31.  32.  33.  34.  35.  36.  37.  38.  39.]
[[  0.   1.   2.   3.]
 [  4.   5.   6.   7.]
 [  8.   9.  10.  11.]
 [ 12.  13.  14.  15.]
 [ 16.  17.  18.  19.]
 [ 20.  21.  22.  23.]
 [ 24.  25.  26.  27.]
 [ 28.  29.  30.  31.]
 [ 32.  33.  34.  35.]
 [ 36.  37.  38.  39.]]


In [5]:
i = 3
onehot = np.zeros(vocab_size)
onehot[i] = 1.
onehot

array([ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.])

In [6]:
embedding_vector = np.dot(onehot, embedding)
print(embedding_vector)

[ 12.  13.  14.  15.]


In [7]:
print(embedding[i])

[ 12.  13.  14.  15.]


In [8]:
from tensorflow.contrib import keras
from keras.layers import Embedding

embedding_layer = Embedding(
    output_dim=embedding_size, input_dim=vocab_size,
    input_length=1, name='my_embedding')

Using TensorFlow backend.


In [10]:
from keras.layers import Input
from keras.models import Model

x = Input(shape=[1], name='input')
embedding = embedding_layer(x)
model = Model(inputs=x, outputs=embedding)
model.output_shape

(None, 1, 4)

In [11]:
model.get_weights()

[array([[ 0.01890775,  0.00499418, -0.03474957,  0.02684459],
        [ 0.0318494 , -0.04652676, -0.02924601,  0.04009086],
        [-0.03589082,  0.0474348 , -0.04485966,  0.00298793],
        [-0.02304914,  0.01285596, -0.03610522, -0.00133644],
        [-0.04690611, -0.0206648 ,  0.0260491 , -0.01262562],
        [ 0.01401315,  0.03188027, -0.02592033, -0.01135837],
        [-0.00707678, -0.01920606,  0.01314666,  0.04426006],
        [-0.02399683,  0.04837314, -0.03009446, -0.00333629],
        [ 0.02805784, -0.01677012, -0.0288386 , -0.00996032],
        [ 0.01646114, -0.03790113, -0.01738508, -0.04946321]], dtype=float32)]

In [12]:
model.predict([[0],
               [3]])

array([[[ 0.01890775,  0.00499418, -0.03474957,  0.02684459]],

       [[-0.02304914,  0.01285596, -0.03610522, -0.00133644]]], dtype=float32)

In [14]:
from keras.layers import Flatten

x = Input(shape=[1], name='input')

# Add a flatten layer to remove useless "sequence" dimension
y = Flatten()(embedding_layer(x))

model2 = Model(inputs=x, outputs=y)
model2.output_shape

(None, 4)

In [15]:
model2.predict([[0],
                [3]])

array([[ 0.01890775,  0.00499418, -0.03474957,  0.02684459],
       [-0.02304914,  0.01285596, -0.03610522, -0.00133644]], dtype=float32)